import 'package:flutter/material.dart';

const String splashPage = '/';
const String mainPage = '/main_page';
const String tabBox = '/tab_page';
const String loginPage = '/login_page';
const String signUpPage = '/sign_up_page';
const String onBoarding = '/on_boarding';
const String signInOrSignUp = '/choose';
const String noInternetRoute = '/no_internet_route';
const String notificationRoute = '/notification_route';
const String favouritesRoute = '/favourites_route';
const String topDoctorsRoute = '/topDoctors_route';
const String doctorsSearchRoute = '/doctors_search_route';
const String specialistsRoute = '/specialists_route';
const String doctorDetailRoute = '/doctor_detail_route';
const String reviewsRoute = '/reviews_route';
const String bookAppointmentRoute = '/book_appointment_route';
const String bookPatientDetailsRoute = '/book_patient_details_route';
const String bookPaymentRoute = '/book_payment_route';
const String myAppointmentDetailRoute = '/my_appointment_detail_route';
const String profileEditRoute = '/profile_edit_route';
const String forgotPasswordRoute = '/forgot_password_route';
const String messageAppointmentRoute = '/message_appointment_route';
const String callAppointmentRoute = '/call_appointment_route';
const String callEndRoute = '/call_end_route';
const String videoCallAppointmentRoute = '/video_call_appointment_route';
const String profiletRoute = '/profile_route';
const String addReviewRoute = '/add_review_route';
const String historyMessageDetailRoute = '/history_message_detail_route';
const String historyRoute = '/history_route';
const String historyCallDetailRoute = '/history_call_detail_route';
const String helpRoute = '/help_route';
const String faqRoute = '/faq_route';
const String contactUsRoute = '/contact_us_route';
const String privacyPolicyRoute = '/privacy_policy_route';
const String termsOfConditionsRoute = '/terms_of_conditions_route';
const String settingsNotif = '/settings_notification';
const String settingsSecure = '/settings_secure';
const String settingsAppear = '/settings_appearance';
const String appearanceRoute = '/appearance_route';
const String languageRoute = '/language_route';
const String specialDoctor = '/special_doctor_route';


myHeight(context) => MediaQuery.of(context).size.height;
myWidth(context) => MediaQuery.of(context).size.width;
